/*
 * Card recognition demo: friend's 3-head CNN (rank / suit / joker) on the FPGA.
 *
 * SNAPSHOT MODE. Nothing runs until KEY0 is pressed. Then: trigger the
 * D8M snapshot -> wait for snapshot_done (capture_384.v has written the 384x384
 * image straight into the CNN's image RAM) -> start the CNN -> poll done
 * (~1.7 s) -> decode rank/suit/joker -> show + print -> wait for the next
 * press. The HDMI preview stays live throughout, so re-aim between presses.
 *
 * HDMI DASHBOARD (hdmi_gui.c). The preview sits top left; the fabric's text
 * layer around it shows the last card, a newest-first history and a 52-card
 * grid of everything seen. KEY1 undoes the newest card (a misread); holding it
 * KEY1_CLEAR_MS clears the lot.
 *
 * This replaced a free-running loop. At 384x384 one inference is ~83 M cycles
 * with 8 conv1 filters (conv_layer.v's table), ~1.7 s at 50 MHz, so running it
 * continuously is exactly the load the snapshot flow exists to avoid.
 *
 * DDR3. fc_shared's weights live in HPS DDR3 (load_fcs_weights_to_ddr) and the
 * fabric fetches them through the f2h_sdram0 port. That freed on-chip memory
 * is what allows 8 conv1 filters and full 8-bit input.
 *
 * FRAMING IS THE WHOLE BALL GAME. The model is trained on the card's rank/suit
 * INDEX CORNER, not the whole card -- the top-left 50% x 35.7% of a
 * perspective-corrected card (friend's build_warped_dataset.py corner_crops(),
 * square now, to match the fabric's square window). On the 96x96 build, the
 * corner read my_deck 54/54 and the whole card 4/54.
 *
 * So aim that corner into the green box on the HDMI output. The box is a
 * 192x192 screen square: 384x384 camera pixels at the display's 2x decimation.
 * It spans twice the card width the 96x96 build's box did, which buys aim
 * tolerance, and training's +/-5% translation covers small misses.
 *
 * Run-time switches, read on every press -- no rebuild:
 *   SW0  print a 48x48 ASCII preview of what was captured
 *   SW1  dump the full 384x384 capture as a PGM for sim_card_cnn.py (slow)
 *
 * PIO base addresses are the lab's; only widths and bit layouts changed
 * (see ghrd_top.v). printf goes to the Arm DS App Console (semihosting).
 */
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include "socal.h"
#include "hps_0_arm_a9_0.h"      /* BUTTON_PIO_BASE, DIPSW_PIO_BASE */

#include "app_config.h"
#include "card_pipeline.h"
#include "hdmi_gui.h"
/* fc_shared's weights, generated by export_weights_rtl.py --hps_header. Missing
 * file = not exported yet; a stale one = the board runs old weights, so export
 * it together with the .hex files every time. */
#include "fcs_w_ddr.h"

_Static_assert(FCS_W_COUNT == 64u * 2305u,
               "fcs_w_ddr.h is not fc_shared's 64 x 2305 weight matrix");

/* Arm DS switches semihosting on whenever a loaded image has this symbol, and
 * semihosting traps every SVC -- including FreeRTOS's task switches, which is
 * what froze CPU0 on 26 Sep. So only the SEMIHOSTED=1 build may define it; the
 * default build prints over HPS UART0 (uart_console.c). */
#ifdef PRINTF_HOST
int __auto_semihosting;
#endif

#define IMG_WR_CTRL_PIO_BASE      (0xFF200000)   /* [2] colour override en, [3] colour override val */
#define CAMERA_TRIGGER_PIO_BASE   (0xFF200030)
#define SNAPSHOT_DATA_PIO_BASE    (0xFF200040)   /* Q6.10 pixel, or a diagnostic at IMG_PIXELS + n */
#define SNAPSHOT_ADDR_PIO_BASE    (0xFF200050)   /* 18 bits: 0..147455 pixels, then diagnostics */
#define CNN_START_PIO_BASE        (0xFF200060)
#define CNN_RESULT_PIO_BASE       (0xFF200070)
/* IMG_WR_DATA (0xFF200010) and IMG_WR_ADDR (0xFF200020) stopped carrying pixels
 * with the 384x384 build (the fabric writes the image RAM itself); they are now
 * the HDMI text layer's write port, driven only by hdmi_gui.c on CPU0.
 * IMG_WR_CTRL stays this file's -- infer() below, which runs on CPU1 in the
 * RTOS build -- so the two cores never share a register.
 * The diagnostic addresses and status bits are in card_pipeline.h. */

/* Experiment switches - no FPGA recompile needed.
 *
 * INVERT and NORMALIZE_MINMAX are gone: they were host-side preprocessing, and
 * the host no longer touches a pixel. The model is trained with neither
 * (PIL convert("L") -> ToTensor(), no inversion, no stretch), which is what
 * capture_384.v writes. */
#define COLOUR_OVERRIDE   1   /* 1: software decides red/black from red_count instead of the hardware flag */
#define RED_THRESH_SW     1500u

/* Camera-link diagnostics (vs/pixclk/retries) -- present since the camera_capture.v
 * that added them. On a bitstream without them they read back as 0, which is
 * indistinguishable from a dead link, so this gates the report. */
#define HAVE_CAM_DIAG     1

/* One inference is ~1.7 s (~1 s with 4 conv1 filters); 5 s still catches a
 * wedged core. Timed on the A9 global timer rather than a loop count, because
 * a bridge read takes an unmeasured fraction of a microsecond, which leaves a
 * loop count little margin either way. */
#define INFER_TIMEOUT_US  5000000u

/* SW_PREVIEW / SW_PGM / SW_STATS (dipsw_pio bits) are in card_pipeline.h. */

/* Every PREVIEW_STEP-th pixel each way: a 48x48 look at the 384x384 capture
 * for ~7,000 bridge accesses. Enough to see the framing and to catch a blank
 * frame, at a fraction of reading all 147,456 pixels. */
#define PREVIEW_STEP      8

/* The hardware flag trips at red_count > RED_THRESH (1536 in capture_384.v),
 * ~1% of the 384x384 crop. A face card's illustration is red and gold, and the
 * red flag locks the suit argmax to {H,D} (card_cnn_core.v) before the net gets
 * a say, so the threshold matters as much as the network.
 *
 * MEASURED 26 Sep 2026 (first M2 board run). The old 12800 -- the 96x96 value
 * scaled 8x with the crop, never measured -- sat above a real red card: black
 * cards read red_count 4..36, a red 10 read 4668, and was forced black (so its
 * suit came out Spades). 1500 sits between the two groups and next to the
 * fabric's own RED_THRESH of 1536. Still only one red sample: the log prints
 * red_count on every press -- check a few red cards (a face card too) and black
 * ones at the final rig and move this into the middle of the gap. red_count
 * reads saturate at 65535.
 *
 * PROJECT_REPORT.md section 10 gives the hardware equivalent of the Python
 * colour test directly: count pixels over the threshold and compare against 2%
 * of the region -- ~2,950 of the 147,456 pixels in the crop, against the 1,536
 * (1.04%) the fabric uses.
 *
 * Their detector went through seven versions (report section 6). Two of its
 * conclusions the fabric version already satisfies: a brightness floor to stop
 * near-black pixels reading as saturated red (RED_MIN 64 here, theirs 30), and
 * cropping to the index corner so face-card artwork is out of frame -- that
 * single change took them 93% -> 99%. The wider 384x384 window takes in more
 * of the card face than the 96x96 one did, so re-check face cards.
 *
 * The one it does NOT satisfy is per-image white balance. The D8M's greenish
 * cast makes `R > 1.5G` harder to satisfy, so once the artwork is out of frame
 * the failure flips direction: expect red cards to read LOW, not black cards
 * high. If that happens it is the cast, not the threshold -- measure with
 * friends files/trainings/calibrate_color_threshold.py. */

const char *const RANK_NAMES[13] = {"2","3","4","5","6","7","8","9","10","J","Q","K","A"};
const char *const SUIT_NAMES[4]  = {"Spades","Clubs","Hearts","Diamonds"};

/* A9 global timer, defined in a9_startup.c.
 *
 * ulGlobalTimerToUs() scales by ulPeriphClockHz, which only the RTOS startup
 * path filled in. Here it is 0 and the function falls back to 200 MHz -- which
 * is this board's real mpu_periph_clk, as the RTOS build measured and printed.
 * So the microsecond figures are correct as they stand; do not "fix" the
 * fallback. The counter's low 32 bits wrap every ~21 s, so unsigned
 * differences are safe for anything shorter. */
extern void     vRunTimeStatsTimerInit( void );
extern uint32_t ulGlobalTimerNow( void );
extern uint32_t ulGlobalTimerToUs( uint32_t ulTicks );

static void delay(volatile int n) { while (n--) ; }

unsigned snap_read(unsigned addr)
{
    alt_write_word(SNAPSHOT_ADDR_PIO_BASE, addr);
    (void)alt_read_word(SNAPSHOT_DATA_PIO_BASE);          /* registered RAM read: one dummy access */
    return alt_read_word(SNAPSHOT_DATA_PIO_BASE) & 0xFFFFu;
}

/* ---- pipeline stages ---------------------------------------------------- */

/* Set by capture_once() when it fails because the trigger was never accepted,
 * so main() can say "camera clock stopped" rather than "timeout". */
static int cap_no_trigger;

int capture_once(void)
{
    int i;
    unsigned r = 0;

    cap_no_trigger = 0;
    alt_write_word(CAMERA_TRIGGER_PIO_BASE, 1);
    delay(200);
    alt_write_word(CAMERA_TRIGGER_PIO_BASE, 0);

    /* snapshot_done is a level left high by the previous capture: wait for it to
     * drop (trigger accepted), then rise again (next frame captured).
     *
     * If it never drops, the trigger was not accepted: capture_384's FSM runs on
     * MIPI_PIXEL_CLK, so with the camera stopped it never sees the trigger and
     * snapshot_done keeps its old high level. Falling through to the wait below
     * would then "succeed" at once and the CNN would re-classify the PREVIOUS
     * capture still sitting in the image RAM -- the same card on every press. */
    for (i = 0; i < 100000 && RES_SNAP_DONE(alt_read_word(CNN_RESULT_PIO_BASE)); i++) ;
    if (RES_SNAP_DONE(alt_read_word(CNN_RESULT_PIO_BASE))) {
        cap_no_trigger = 1;
        return 0;
    }
    for (i = 0; i < 4000000; i++) {
        r = alt_read_word(CNN_RESULT_PIO_BASE);
        if (RES_SNAP_DONE(r)) return 1;
    }
    return 0;
}

/* Returns the raw result word, or 0 on timeout. Bit 7 (done) is always set in a
 * real result, so 0 is unambiguous. */
unsigned infer(unsigned red_count)
{
    uint32_t t0;
    unsigned r;

    /* ghrd_top.v latches the colour on the start pulse, so set it first */
#if COLOUR_OVERRIDE
    alt_write_word(IMG_WR_CTRL_PIO_BASE, 0x4u | ((red_count > RED_THRESH_SW) ? 0x8u : 0x0u));
#else
    (void)red_count;
    alt_write_word(IMG_WR_CTRL_PIO_BASE, 0);
#endif

    alt_write_word(CNN_START_PIO_BASE, 1);   /* hardware edge-detects start, clears sticky done */
    delay(50);
    alt_write_word(CNN_START_PIO_BASE, 0);

    t0 = ulGlobalTimerNow();
    do {
        r = alt_read_word(CNN_RESULT_PIO_BASE);
        if (RES_DONE(r)) return r;
    } while (ulGlobalTimerToUs(ulGlobalTimerNow() - t0) < INFER_TIMEOUT_US);
    return 0;
}

/* Min/max over the PREVIEW_STEP grid, and the same grid as ASCII art in `art`
 * (PREVIEW_DIM x PREVIEW_DIM, printed later by print_preview on CPU0 -- this
 * runs on CPU1 in the RTOS build, which must not printf). Must run while the
 * core is idle: the image RAM's read port is conv1's during inference and a
 * read then returns whatever conv1 is addressing. Same character ramp as the
 * 96x96 build, so a preview still compares against a reference crop. */
static void sample_capture(uint32_t *minv, uint32_t *maxv, char *art)
{
    int i, j;
    unsigned lo = 255u, hi = 0u;

    for (i = 0; i < IMG_DIM; i += PREVIEW_STEP) {
        for (j = 0; j < IMG_DIM; j += PREVIEW_STEP) {
            unsigned g = PIX_GRAY(snap_read((unsigned)(i * IMG_DIM + j)));
            if (g < lo) lo = g;
            if (g > hi) hi = g;
            *art++ = (g <  51u) ? '@' :
                     (g < 102u) ? '#' :
                     (g < 153u) ? '+' :
                     (g < 204u) ? '-' : ' ';
        }
    }
    *minv = lo;
    *maxv = hi;
}

/* One printf per row, not per character: every semihosted call is a debugger
 * round trip. */
void print_preview(const char *art)
{
    char line[PREVIEW_DIM + 2];
    int y, x;

    for (y = 0; y < PREVIEW_DIM; y++) {
        for (x = 0; x < PREVIEW_DIM; x++) line[x] = art[y * PREVIEW_DIM + x];
        line[PREVIEW_DIM] = '\n';
        line[PREVIEW_DIM + 1] = '\0';
        fputs(line, stdout);
    }
}

/* Paste from "P2" to the last number into a file and run it through
 * sim_card_cnn.py: if the sim's logits match the board's, the accelerator is
 * faithful and any error is upstream of it. Each value is the exact pixel conv1
 * read, as gray = q >> 2 (the sim's to_q() rebuilds q losslessly).
 *
 * One printf per ROW rather than per pixel: every semihosted call is a
 * debugger round trip, and 147,456 of them would take minutes. */
void dump_pgm(void)
{
    static char line[IMG_DIM * 4 + 2];
    int y, x;

    printf("--- PGM begin ---\nP2\n%d %d\n255\n", IMG_DIM, IMG_DIM);
    for (y = 0; y < IMG_DIM; y++) {
        char *p = line;
        for (x = 0; x < IMG_DIM; x++) {
            unsigned g = PIX_GRAY(snap_read((unsigned)(y * IMG_DIM + x)));
            if (g >= 100u) *p++ = (char)('0' + g / 100u);
            if (g >=  10u) *p++ = (char)('0' + (g / 10u) % 10u);
            *p++ = (char)('0' + g % 10u);
            *p++ = (x == IMG_DIM - 1) ? '\n' : ' ';
        }
        *p = '\0';
        fputs(line, stdout);
    }
    printf("--- PGM end ---\n\n");
}

void print_result_name(unsigned r)
{
    unsigned rank = RES_RANK(r), suit = RES_SUIT(r);
    if (RES_JOKER(r))    printf("%-14s", "JOKER");
    else if (rank < 13)  printf("%-3s of %-9s", RANK_NAMES[rank], SUIT_NAMES[suit]);
    else                 printf("bad rank %-5u", rank);
}

void print_camera_diag(void)
{
#if !HAVE_CAM_DIAG
    printf("camera diagnostics absent from this bitstream\n");
#else
    unsigned st = snap_read(SNAP_STATUS);
    /* SNAP_CFG_STEP is not printed: MIPI_BRIDGE_CAMERA_Config declares STEP
     * but its .STEP connection is commented out inside that wrapper, so the
     * port is undriven and always reads 0. Use WCNT instead if it is ever
     * brought out. */
    printf("camera: mipi_cfg=%u cam_cfg=%u  vs=%u pixclk=%u retries=%u"
           "   (audpll=%u hdmi=%u)\n",
           ST_MIPI_REL(st), ST_CAM_REL(st),
           snap_read(SNAP_VS_COUNT), snap_read(SNAP_PIXCLK),
           snap_read(SNAP_RETRIES),
           ST_AUDPLL_OK(st), ST_HDMI_RDY(st));
#endif
}

/* The camera is the thing that has actually been failing, so say so plainly
 * rather than letting a blank frame come back as a confident card. */
void check_camera_alive(void)
{
#if !HAVE_CAM_DIAG
    printf("camera diagnostics absent from this bitstream -- recompile\n"
           "camera_capture.v and set HAVE_CAM_DIAG to read vs/pixclk.\n");
#else
    unsigned vs0, vs1, pix0, pix1;
    volatile int i;

    print_camera_diag();

    vs0  = snap_read(SNAP_VS_COUNT);
    pix0 = snap_read(SNAP_PIXCLK);
    for (i = 0; i < 2000000; i++) ;              /* short settle, tens of ms */
    vs1  = snap_read(SNAP_VS_COUNT);
    pix1 = snap_read(SNAP_PIXCLK);

    if (vs1 == vs0) {
        printf("\n*** WARNING: no MIPI frames (vs_count stuck at %u) ***\n", vs1);
        /* The bridge only emits MIPI_PIXEL_CLK once the sensor is streaming,
         * and the camera LUT ends with "wake up, streaming" -- so pixclk=0
         * with cam_cfg=0 is a CONSEQUENCE of the config never finishing, not
         * independent evidence of a dead link. Only call the link dead when
         * the config actually completed. */
        if (pix1 == pix0 && !ST_CAM_REL(snap_read(SNAP_STATUS)))
            printf("    camera I2C config never completes, so the sensor never\n"
                   "    streams and the bridge has nothing to clock out.\n"
                   "    Note the bridge bus IS fine (mipi_cfg=1): this is the\n"
                   "    separate CAMERA_I2C bus or the sensor itself.\n");
        else if (pix1 == pix0)
            printf("    config completed but no pixel clock -> link down: reseat\n"
                   "    the D8M; the module or cable is at fault.\n");
        else
            printf("    pixel clock runs but no frames -> bridge clocks without\n"
                   "    framing; wrong lane count or format.\n");
        printf("    Every prediction below is the network's answer to a blank image.\n\n");
    } else {
        /* Frame rate and pixel clock over ~1 s of the A9 global timer. This
         * confirms the sensor mode (640x480 @ ~60 fps expected) and measures
         * the MIPI_PIXEL_CLK frequency the SDC still lacks a create_clock for.
         * pixclk ticks once per 32,768 pixel clocks; both counters are 16-bit
         * with no reset, so the deltas are taken mod 2^16. */
        uint32_t t0 = ulGlobalTimerNow(), us;
        unsigned dvs, dpix, fps_x10, khz;

        vs0  = snap_read(SNAP_VS_COUNT);
        pix0 = snap_read(SNAP_PIXCLK);
        do {
            us = ulGlobalTimerToUs(ulGlobalTimerNow() - t0);
        } while (us < 1000000u);
        vs1  = snap_read(SNAP_VS_COUNT);
        pix1 = snap_read(SNAP_PIXCLK);
        us   = ulGlobalTimerToUs(ulGlobalTimerNow() - t0);

        dvs     = (vs1 - vs0) & 0xFFFFu;
        dpix    = (pix1 - pix0) & 0xFFFFu;
        fps_x10 = (unsigned)((uint64_t)dvs * 10000000u / us);
        khz     = (unsigned)((uint64_t)dpix * 32768u * 1000u / us);
        printf("camera: %u.%u fps, pixel clock ~%u.%u MHz (MIPI_PIXEL_CLK, for the SDC)\n",
               fps_x10 / 10u, fps_x10 % 10u, khz / 1000u, (khz % 1000u) / 100u);
    }
#endif
}

/* ---- one job, shared by the single-core loop and both RTOS cores ---------- */

void vision_run(struct vision_result *v)
{
    uint32_t t0 = ulGlobalTimerNow();

    v->result = 0;
    v->red_count = 0;
    v->minv = v->maxv = 0;
    v->cap_us = v->inf_us = 0;

    if (!capture_once()) {
        v->status = cap_no_trigger ? VIS_NO_TRIGGER : VIS_CAP_TIMEOUT;
        return;
    }
    v->cap_us = ulGlobalTimerToUs(ulGlobalTimerNow() - t0);
    v->red_count = snap_read(SNAP_RED_COUNT);

    /* before the start pulse: the core owns the image RAM's read port after it */
    sample_capture(&v->minv, &v->maxv, v->art);

    t0 = ulGlobalTimerNow();
    v->result = infer(v->red_count);
    v->inf_us = ulGlobalTimerToUs(ulGlobalTimerNow() - t0);
    v->status = v->result ? VIS_OK : VIS_INFER_TIMEOUT;
}

void print_vision_result(unsigned shot, const struct vision_result *v, const char *where)
{
    unsigned r = v->result;

    printf("[%4u] ", shot);
    switch (v->status) {
    case VIS_NO_TRIGGER:
        printf("trigger not accepted - camera pixel clock stopped (old image NOT classified)");
        break;
    case VIS_CAP_TIMEOUT:
        printf("snapshot timeout - camera not streaming");
        break;
    case VIS_INFER_TIMEOUT:
        printf("inference timeout (> %u ms)", INFER_TIMEOUT_US / 1000u);
        break;
    default:
        if (RES_DDR_ERR(r)) {
            printf("DDR3 weight fetch timed out -- the FPGA-to-SDRAM port is not answering.\n"
                   "       The preloader (u-boot-spl.axf) must configure f2h_sdram0: rebuild it\n"
                   "       from hps_isw_handoff after the Quartus compile. No card was read.");
        } else {
            print_result_name(r);
            printf("  logit %5d  red %5u->%-5s  min %3u max %3u  | cap %lu us  inf %lu ms",
                   RES_SCORE(r), (unsigned)v->red_count, RES_COLOUR(r) ? "red" : "black",
                   (unsigned)v->minv, (unsigned)v->maxv,
                   (unsigned long)v->cap_us, (unsigned long)(v->inf_us / 1000u));
            if (v->maxv == 0u) printf("   <- BLANK FRAME");
        }
        break;
    }
    if (where) printf("  [%s]", where);
    putchar('\n');

    if (v->status == VIS_NO_TRIGGER || v->status == VIS_CAP_TIMEOUT)
        print_camera_diag();
}

/* fc_shared's 147,520 weights live in HPS DDR3, not on chip -- the fabric reads
 * them through the f2h_sdram0 port (card_cnn_core.v). Put them there once, at
 * startup: one sign-extended Q6.10 value per 32-bit word at FCS_W_DDR_BASE,
 * the layout the professor's sdram_master reads (low halfword of each word).
 *
 * No cache maintenance is needed: this bare-metal app never enables the caches
 * or the MMU, so the stores go straight to DDR3. The dsb only makes sure they
 * have all left the CPU before the fabric can be started.
 *
 * The fpgaportrst write releases the FPGA-to-SDRAM port in case the preloader
 * (u-boot-spl.axf) was built for a system without one and left it in reset.
 * If the port still does not answer, the fabric times out and sets
 * RES_DDR_ERR instead of hanging -- see main(). */
static void load_fcs_weights_to_ddr(void)
{
    volatile uint32_t *dst = (volatile uint32_t *)FCS_W_DDR_BASE;
    unsigned i;

    alt_write_word(SDR_FPGAPORTRST, 0x3FFFu);
    for (i = 0; i < FCS_W_COUNT; i++)
        dst[i] = (uint32_t)(int32_t)FCS_W_Q[i];
    __asm__ volatile ("dsb" ::: "memory");

    printf("fc_shared: %u weights -> DDR3 @ 0x%08x (f2h_sdram0)\n",
           FCS_W_COUNT, FCS_W_DDR_BASE);
}

/* KEY0/KEY1 presses since the last call (bit per key), and clears them.
 *
 * The keys are debounced in fabric (ghrd_top.v debounce_inst, active low), and
 * button_pio has its edge-capture register enabled for FALLING edges -- i.e. a
 * press -- with bit-clearing (write 1 to clear). Reading that register instead
 * of polling the key level means a press is latched in hardware and never
 * missed, including one that comes and goes while CPU0 is halted inside a
 * semihosted printf (the debugger stops the core for every console call, so a
 * level poll missed any press made while results were printing). */
#define BUTTON_EDGECAP   (BUTTON_PIO_BASE + 0xC)   /* PIO register 3: edgecapture */

unsigned key_presses(void)
{
    unsigned e = alt_read_word(BUTTON_EDGECAP) & 0x3u;

    if (e)
        alt_write_word(BUTTON_EDGECAP, e);
    return e;
}

/* The keys down right now (the debounced level, active low) -- for timing how
 * long KEY1 is held. */
unsigned keys_held(void)
{
    return ~alt_read_word(BUTTON_PIO_BASE) & 0x3u;
}

unsigned read_switches(void)
{
    return alt_read_word(DIPSW_PIO_BASE) & 0xFu;
}

#if !RTOS_MODE
/* Block until a press is latched; returns which keys. A press made while the
 * previous card was still being read is kept, so it runs straight after. */
static unsigned wait_for_press(void)
{
    unsigned k;

    while (!(k = key_presses())) ;
    return k;
}

/* KEY1 was pressed: undo the newest card on release, or clear the tracker if it
 * is still down after KEY1_CLEAR_MS. */
static void key1_undo_or_clear(void)
{
    uint32_t t0 = ulGlobalTimerNow();

    while (keys_held() & KEY_UNDO) {
        if (ulGlobalTimerToUs(ulGlobalTimerNow() - t0) >= KEY1_CLEAR_MS * 1000u) {
            gui_clear();
            return;
        }
    }
    gui_undo();
}
#endif

int main(void)
{
#ifndef PRINTF_HOST
    uart_console_init();        /* console on HPS UART0 -- before the first printf */
#endif
    vRunTimeStatsTimerInit();
    load_fcs_weights_to_ddr();
    check_camera_alive();
    (void)key_presses();        /* drop presses latched before the app started */

#if RTOS_MODE
    /* FreeRTOS on CPU0 + vision worker on CPU1: app_rtos.c. Set RTOS_MODE 0 in
     * app_config.h for the single-core loop below. */
    return rtos_main();
#else
    {
        static struct vision_result v;
        unsigned shot = 0;

        gui_init();
        printf("snapshot mode -- press KEY0 to capture and classify; the HDMI dashboard\n"
               "tracks each card. KEY1 undoes the newest one (hold %u ms: clear them all).\n"
               "SW0 = ASCII preview, SW1 = PGM dump for sim_card_cnn.py.\n\n",
               (unsigned)KEY1_CLEAR_MS);

        for (;;) {
            unsigned sw, keys;

            keys = wait_for_press();
            if (keys & KEY_UNDO)
                key1_undo_or_clear();
            if (!(keys & KEY_CAPTURE))
                continue;
            sw = read_switches();

            gui_status("READING", GUI_YELLOW);
            vision_run(&v);
            gui_job_done(shot, &v, 1, NULL);        /* HDMI first: the prints are slow */
            if ((sw & SW_PREVIEW) && (v.status == VIS_OK || v.status == VIS_INFER_TIMEOUT))
                print_preview(v.art);
            print_vision_result(shot++, &v, NULL);
            /* only once the core is done: until then the image read port is conv1's */
            if ((sw & SW_PGM) && v.status == VIS_OK && !RES_DDR_ERR(v.result)) {
                gui_status("PGM DUMP (console)", GUI_YELLOW);
                dump_pgm();
                gui_status("READY", GUI_LGREEN);
            }
        }
    }
#endif
}
